import { toSlug } from "@/lib/utils";

// Demo catalog used by `npm run seed`. Photos live in public/images/products/<slug>/:
// studio shots on white are 1.webp, 2.webp…; on-model photos are look-1.jpg, look-2.jpg…
// (see isLookPhoto in lib/utils.ts).

type Tag = "new-arrival" | "best-seller" | "todays-deal" | "featured";

type SeedProduct = {
  name: string;
  brand: string;
  category: string;
  price: number;
  listPrice?: number;
  countInStock: number;
  numSales: number;
  tags: Tag[];
  sizes: string[];
  colors: string[];
  description: string;
  /** Studio shots (n.webp). */
  shots?: number;
  /** On-model photos (look-n.jpg), shown after the studio shots. */
  looks?: number;
};

const CLOTHING = ["XS", "S", "M", "L", "XL", "XXL"];
const MEN_SHOES = ["40", "41", "42", "43", "44", "45"];
const WOMEN_SHOES = ["36", "37", "38", "39", "40", "41"];
const WAIST = ["28", "30", "32", "34", "36", "38"];
const BELT = ["85 cm", "90 cm", "95 cm", "100 cm", "105 cm", "110 cm"];

const catalog: SeedProduct[] = [
  // ---------- Shirts ----------
  {
    name: "Gingham Check Oxford Shirt",
    brand: "Urban Thread",
    category: "Shirts",
    price: 34.99,
    listPrice: 44.99,
    countInStock: 42,
    numSales: 61,
    tags: ["featured", "todays-deal"],
    sizes: CLOTHING.slice(1),
    colors: ["Blue", "White"],
    shots: 4,
    description:
      "A sharp blue-and-white gingham shirt cut from breathable cotton oxford. Button-down collar, curved hem and a single chest-free front make it easy to wear tucked into chinos or loose over jeans. Machine washable and easy to iron.",
  },
  {
    name: "Buffalo Plaid Flannel Shirt",
    brand: "Northfield",
    category: "Shirts",
    price: 39.99,
    countInStock: 35,
    numSales: 88,
    tags: ["best-seller"],
    sizes: CLOTHING.slice(1),
    colors: ["Red", "Black"],
    shots: 4,
    description:
      "Brushed cotton flannel in the classic red-and-black buffalo check. Soft, warm and a little heavier than a regular shirt, so it works on its own or as a layer over a tee. Relaxed fit with a point collar and buttoned cuffs.",
  },
  {
    name: "Tropical Hibiscus Short-Sleeve Shirt",
    brand: "Casa Brisa",
    category: "Shirts",
    price: 27.99,
    listPrice: 34.99,
    countInStock: 48,
    numSales: 37,
    tags: ["new-arrival", "todays-deal"],
    sizes: CLOTHING.slice(1),
    colors: ["Blue"],
    shots: 4,
    description:
      "Lightweight viscose resort shirt with an all-over blue hibiscus and palm print. Camp collar, straight hem and a loose, breezy fit made for hot days, beach trips and summer evenings.",
  },
  {
    name: "Tartan Check Button-Down Shirt",
    brand: "Urban Thread",
    category: "Shirts",
    price: 32.99,
    countInStock: 30,
    numSales: 24,
    tags: ["new-arrival"],
    sizes: CLOTHING.slice(1),
    colors: ["Green", "Grey"],
    shots: 4,
    description:
      "A soft cotton twill shirt in a muted green-and-teal tartan. Regular fit, button-down collar and a longer back hem that stays tucked in. Pairs well with dark denim and suede boots.",
  },

  // ---------- Pants (jeans + trousers, on-model photos) ----------
  {
    name: "High-Rise Dark Wash Bootcut Jeans",
    brand: "Denim Lab",
    category: "Pants",
    price: 54.99,
    countInStock: 38,
    numSales: 142,
    tags: ["best-seller", "featured"],
    sizes: WAIST,
    colors: ["Dark Blue"],
    looks: 4,
    description:
      "A flattering high-rise bootcut in deep indigo stretch denim. Sits at the natural waist, skims the thigh and opens into a subtle flare that balances heels and trainers alike. Classic five-pocket styling, 32\" inseam.",
  },
  {
    name: "Light Wash Wide-Leg Flare Jeans",
    brand: "Denim Lab",
    category: "Pants",
    price: 59.99,
    listPrice: 74.99,
    countInStock: 29,
    numSales: 97,
    tags: ["todays-deal", "best-seller"],
    sizes: WAIST,
    colors: ["Light Blue"],
    looks: 4,
    description:
      "70s-inspired flares in a sun-faded light wash. Super high rise, a fitted hip and a dramatic wide flare from the knee. 100% cotton rigid denim that softens with every wear.",
  },
  {
    name: "Relaxed Baggy Boyfriend Jeans",
    brand: "Northfield",
    category: "Pants",
    price: 49.99,
    countInStock: 44,
    numSales: 76,
    tags: ["new-arrival"],
    sizes: WAIST,
    colors: ["Light Blue"],
    looks: 4,
    description:
      "Slouchy, low-slung boyfriend jeans with a roomy leg and a pooled hem. Soft vintage wash with light whiskering. Style with a cropped jacket or an oversized shirt for an easy weekend look.",
  },
  {
    name: "Light Wash High-Rise Skinny Jeans",
    brand: "Denim Lab",
    category: "Pants",
    price: 44.99,
    countInStock: 51,
    numSales: 118,
    tags: ["best-seller"],
    sizes: WAIST,
    colors: ["Light Blue"],
    looks: 4,
    description:
      "Our best-selling skinny in a clean light wash. Power-stretch denim holds its shape all day, while the high rise and ankle length keep it looking sharp with sneakers or heels.",
  },
  {
    name: "Distressed Ripped Boyfriend Jeans",
    brand: "Street Denim Co.",
    category: "Pants",
    price: 52.99,
    listPrice: 64.99,
    countInStock: 23,
    numSales: 58,
    tags: ["todays-deal"],
    sizes: WAIST,
    colors: ["Blue"],
    looks: 3,
    description:
      "Heavily distressed boyfriend jeans with open rips at the knees and thighs, raw frayed edges and a mid-blue wash. A relaxed, lived-in fit with plenty of attitude.",
  },
  {
    name: "Denim Cargo Wide-Leg Jeans",
    brand: "Street Denim Co.",
    category: "Pants",
    price: 62.99,
    countInStock: 27,
    numSales: 34,
    tags: ["new-arrival", "featured"],
    sizes: WAIST,
    colors: ["Blue"],
    looks: 4,
    description:
      "Utility meets denim: a wide, straight leg with oversized flap cargo pockets and a mid-rise waist. Made from sturdy 13 oz cotton in a bright mid-blue wash.",
  },
  {
    name: "Men's Relaxed Light Wash Jeans",
    brand: "Northfield",
    category: "Pants",
    price: 49.99,
    countInStock: 40,
    numSales: 63,
    tags: ["best-seller"],
    sizes: WAIST,
    colors: ["Light Blue"],
    looks: 3,
    description:
      "An easy relaxed fit through the seat and thigh with a straight leg. Light stone wash, a button fly and reinforced pockets for everyday wear.",
  },
  {
    name: "Men's Olive Slim Cargo Trousers",
    brand: "Urban Thread",
    category: "Pants",
    price: 46.99,
    countInStock: 36,
    numSales: 81,
    tags: ["best-seller", "featured"],
    sizes: WAIST,
    colors: ["Olive"],
    looks: 3,
    description:
      "Smart-casual cargos in a soft cotton twill with a touch of stretch. Slim tapered leg, flat side cargo pockets and a clean waistband that works with a belt and an oxford shirt.",
  },
  {
    name: "Men's Khaki Cargo Chinos",
    brand: "Urban Thread",
    category: "Pants",
    price: 42.99,
    listPrice: 54.99,
    countInStock: 33,
    numSales: 47,
    tags: ["todays-deal"],
    sizes: WAIST,
    colors: ["Khaki"],
    looks: 3,
    description:
      "Relaxed khaki chinos with discreet cargo pockets and elasticated cuffs you can wear long or scrunched. Washed cotton for a broken-in feel from day one.",
  },
  {
    name: "Men's White Utility Cargo Pants",
    brand: "Street Denim Co.",
    category: "Pants",
    price: 48.99,
    countInStock: 19,
    numSales: 22,
    tags: ["new-arrival"],
    sizes: WAIST,
    colors: ["White"],
    looks: 3,
    description:
      "Crisp white cargo pants in heavyweight cotton canvas. Straight leg, multiple utility pockets and an adjustable hem. A fresh summer staple with a vest or an overshirt.",
  },
  {
    name: "Men's Tan Stretch Chinos",
    brand: "Northfield",
    category: "Pants",
    price: 39.99,
    countInStock: 45,
    numSales: 69,
    tags: ["featured"],
    sizes: WAIST,
    colors: ["Tan"],
    looks: 3,
    description:
      "Skinny-fit chinos in a warm tan with 2% elastane for comfort. Slant front pockets, welt back pockets and a clean hem. Dress them up with a blazer or keep it casual with a denim jacket.",
  },
  {
    name: "Men's Black Parachute Cargo Pants",
    brand: "Street Denim Co.",
    category: "Pants",
    price: 55.99,
    countInStock: 26,
    numSales: 31,
    tags: ["new-arrival", "featured"],
    sizes: CLOTHING.slice(1),
    colors: ["Black"],
    looks: 4,
    description:
      "Lightweight nylon parachute pants with a loose, balloon-shaped leg, toggle hems and zipped cargo pockets. Streetwear comfort that moves with you.",
  },
  {
    name: "Women's Olive Wide Cargo Pants",
    brand: "Urban Chic",
    category: "Pants",
    price: 51.99,
    listPrice: 64.99,
    countInStock: 21,
    numSales: 54,
    tags: ["todays-deal", "featured"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Olive"],
    looks: 4,
    description:
      "High-waisted cargo pants in army-olive cotton with a button fly, oversized patch pockets and an ultra-wide leg. Pair with a crop top and chunky boots.",
  },
  {
    name: "Grey High-Waist Wide-Leg Trousers",
    brand: "Linea",
    category: "Pants",
    price: 57.99,
    countInStock: 18,
    numSales: 26,
    tags: ["new-arrival"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Grey"],
    looks: 3,
    description:
      "Tailored charcoal trousers with a sharp front crease, a high waist and a fluid wide leg. Made from a wool-feel suiting fabric that drapes beautifully.",
  },

  // ---------- Belts ----------
  {
    name: "Classic Black Leather Belt with Brass Buckle",
    brand: "Beltley",
    category: "Belts",
    price: 34.99,
    countInStock: 60,
    numSales: 124,
    tags: ["best-seller"],
    sizes: BELT,
    colors: ["Black"],
    looks: 4,
    description:
      "Full-grain black leather, 3.5 cm wide, with an antique brass horseshoe buckle and stitched edges. The one belt that goes with jeans and suits alike.",
  },
  {
    name: "Red Croc-Embossed Leather Belt",
    brand: "Beltley",
    category: "Belts",
    price: 44.99,
    countInStock: 22,
    numSales: 28,
    tags: ["new-arrival"],
    sizes: BELT,
    colors: ["Red"],
    looks: 3,
    description:
      "A statement belt in glossy cherry-red leather with a bold crocodile emboss and a polished gold buckle. Adds instant colour to black and denim outfits.",
  },
  {
    name: "Black Tooled Leather Western Belt",
    brand: "Beltley",
    category: "Belts",
    price: 49.99,
    listPrice: 59.99,
    countInStock: 25,
    numSales: 41,
    tags: ["todays-deal", "featured"],
    sizes: BELT,
    colors: ["Black"],
    looks: 4,
    description:
      "Hand-tooled black leather with a raised floral pattern and a gold-tone roller buckle. Western character with a refined finish.",
  },
  {
    name: "Sky Blue Croc-Embossed Belt",
    brand: "Beltley",
    category: "Belts",
    price: 42.99,
    countInStock: 17,
    numSales: 15,
    tags: ["new-arrival"],
    sizes: BELT,
    colors: ["Light Blue"],
    looks: 4,
    description:
      "Soft sky-blue leather with a matte croc texture and a brushed gold buckle. A fresh accent for white jeans, linen trousers and summer dresses.",
  },
  {
    name: "Cognac Croc Belt with Leopard Buckle",
    brand: "Beltley",
    category: "Belts",
    price: 64.99,
    countInStock: 12,
    numSales: 19,
    tags: ["featured"],
    sizes: BELT,
    colors: ["Brown", "Silver"],
    looks: 4,
    description:
      "Cognac croc-embossed leather finished with a sculpted silver leopard-head plate buckle. A conversation piece for the man who likes his details bold.",
  },
  {
    name: "Men's Tan Leather Dress Belt",
    brand: "Northfield",
    category: "Belts",
    price: 29.99,
    listPrice: 39.99,
    countInStock: 48,
    numSales: 88,
    tags: ["todays-deal", "best-seller"],
    sizes: BELT,
    colors: ["Tan"],
    looks: 4,
    description:
      "A slim 3 cm tan leather belt with a brushed silver pin buckle. Smart enough for a shirt and tie, relaxed enough for chinos on the weekend.",
  },
  {
    name: "Women's Wide Silver Buckle Waist Belt",
    brand: "Maison Lune",
    category: "Belts",
    price: 38.99,
    countInStock: 20,
    numSales: 33,
    tags: ["featured"],
    sizes: ["S", "M", "L"],
    colors: ["Silver"],
    looks: 4,
    description:
      "A wide metallic waist belt with a chunky rectangular buckle. Cinch it over a blazer, a coat or an oversized dress to define your silhouette.",
  },
  {
    name: "Red D-Ring Webbing Belt",
    brand: "Urban Chic",
    category: "Belts",
    price: 19.99,
    countInStock: 55,
    numSales: 47,
    tags: ["new-arrival"],
    sizes: ["One Size"],
    colors: ["Red"],
    looks: 3,
    description:
      "A sporty red canvas webbing belt with a double D-ring closure and a long hanging tail. Fully adjustable, lightweight and fun.",
  },

  // ---------- Shoes ----------
  {
    name: "Air Jordan 1 Mid Chicago",
    brand: "Nike",
    category: "Shoes",
    price: 149.99,
    countInStock: 22,
    numSales: 134,
    tags: ["best-seller", "featured"],
    sizes: MEN_SHOES,
    colors: ["Red", "White", "Black"],
    shots: 4,
    description:
      "The icon in its most famous colourway. Quilted red leather overlays on a white base, a padded mid-top collar and an Air-Sole unit in the heel for all-day cushioning. Rubber cupsole with a pivot circle for grip.",
  },
  {
    name: "Future Rider Play On Trainers",
    brand: "Puma",
    category: "Shoes",
    price: 89.99,
    listPrice: 109.99,
    countInStock: 31,
    numSales: 57,
    tags: ["todays-deal"],
    sizes: MEN_SHOES,
    colors: ["Blue", "Red", "Yellow"],
    shots: 4,
    description:
      "Retro running style with a modern, lightweight build. Mixed suede and nylon upper in bold primary colours, a soft EVA midsole and a rubber outsole with a deep tread for city miles.",
  },
  {
    name: "Out Of Office Low-Top Sneakers",
    brand: "Off-White",
    category: "Shoes",
    price: 219.99,
    countInStock: 14,
    numSales: 29,
    tags: ["new-arrival", "featured"],
    sizes: MEN_SHOES,
    colors: ["White", "Red"],
    shots: 4,
    description:
      "Clean white calf leather with the signature red arrow on the side and a contrast red heel tab. Padded collar, perforated toe box and a vintage-effect rubber sole. Comes with a spare set of laces.",
  },
  {
    name: "Pointed-Toe Leather Pumps",
    brand: "Maison Lune",
    category: "Shoes",
    price: 69.99,
    countInStock: 26,
    numSales: 73,
    tags: ["best-seller"],
    sizes: WOMEN_SHOES,
    colors: ["Black"],
    shots: 4,
    description:
      "The black pump every wardrobe needs. Smooth leather upper, a sleek pointed toe and a 9 cm stiletto heel, with a cushioned leather footbed for long days at the office or nights out.",
  },
  {
    name: "Strappy Patent Heeled Sandals",
    brand: "Calvin Klein",
    category: "Shoes",
    price: 89.99,
    listPrice: 119.99,
    countInStock: 18,
    numSales: 41,
    tags: ["todays-deal"],
    sizes: WOMEN_SHOES,
    colors: ["Black"],
    shots: 4,
    description:
      "Glossy black patent sandals with a wide logo strap across the toe and a wraparound ankle cuff. The 10 cm heel is balanced by a slightly padded insole. Made for evening dresses and tailored trousers alike.",
  },
  {
    name: "Metallic Gold Stiletto Pumps",
    brand: "Maison Lune",
    category: "Shoes",
    price: 64.99,
    countInStock: 15,
    numSales: 33,
    tags: ["featured"],
    sizes: WOMEN_SHOES,
    colors: ["Gold"],
    shots: 4,
    description:
      "Mirror-finish gold pumps with a pointed toe and a slim 10 cm heel. A statement shoe for weddings and parties that still goes with simple black outfits. Soft nude lining and a non-slip sole.",
  },
  {
    name: "Classic Nude-Lined Stilettos",
    brand: "Pampi",
    category: "Shoes",
    price: 49.99,
    countInStock: 29,
    numSales: 46,
    tags: ["new-arrival"],
    sizes: WOMEN_SHOES,
    colors: ["Black"],
    shots: 4,
    description:
      "Black leather stilettos with a nude lining and a red-lacquered sole. A deep-cut vamp elongates the leg, and a memory-foam insole keeps them comfortable for longer.",
  },
  {
    name: "Cherry Red Patent Pumps",
    brand: "Maison Lune",
    category: "Shoes",
    price: 54.99,
    listPrice: 69.99,
    countInStock: 21,
    numSales: 38,
    tags: ["todays-deal"],
    sizes: WOMEN_SHOES,
    colors: ["Red"],
    shots: 4,
    description:
      "Bold cherry-red patent pumps with a rounded pointed toe and an 8 cm heel. Add a pop of colour to a monochrome outfit, or go all in with a matching bag.",
  },

  // ---------- Bags ----------
  {
    name: "Structured Navy Tote Bag",
    brand: "Fashionista",
    category: "Bags",
    price: 59.99,
    countInStock: 33,
    numSales: 64,
    tags: ["best-seller"],
    sizes: [],
    colors: ["Navy"],
    shots: 3,
    description:
      "A roomy everyday tote in deep navy faux leather. The structured shape holds a 13-inch laptop, and inside you get a zip pocket and two slip pockets for your phone and keys. Magnetic top closure.",
  },
  {
    name: "Cognac Leather Hobo Bag",
    brand: "Heshe",
    category: "Bags",
    price: 129.99,
    listPrice: 159.99,
    countInStock: 17,
    numSales: 52,
    tags: ["featured", "todays-deal"],
    sizes: [],
    colors: ["Brown"],
    shots: 3,
    description:
      "Soft pebbled cowhide in a warm cognac tone, with gold hardware and a zip pocket on the back. The slouchy hobo shape fits everything you need for the day and gets better with age.",
  },
  {
    name: "Saffiano Leather Double-Zip Tote",
    brand: "Milano Atelier",
    category: "Bags",
    price: 189.99,
    countInStock: 11,
    numSales: 19,
    tags: ["new-arrival", "featured"],
    sizes: [],
    colors: ["Light Blue"],
    shots: 3,
    description:
      "Scratch-resistant saffiano leather in a fresh sky blue. Two zipped compartments with an open centre section, rolled top handles and a detachable shoulder strap. Finished with gold-tone feet to protect the base.",
  },
  {
    name: "Faux Leather Drawstring Backpack",
    brand: "Urban Chic",
    category: "Bags",
    price: 44.99,
    countInStock: 40,
    numSales: 71,
    tags: ["best-seller"],
    sizes: [],
    colors: ["White"],
    shots: 3,
    description:
      "A minimal white backpack with a flap top, drawstring closure and gold bar detail. Adjustable padded straps and an inner laptop sleeve make it as practical for class as it is for the weekend.",
  },
  {
    name: "Black Satchel with Buckle Detail",
    brand: "Elegance",
    category: "Bags",
    price: 69.99,
    listPrice: 84.99,
    countInStock: 24,
    numSales: 43,
    tags: ["todays-deal"],
    sizes: [],
    colors: ["Black"],
    shots: 3,
    description:
      "A polished black satchel with a buckled front strap, expandable side gussets and a detachable crossbody strap. Three inner compartments keep your essentials organised.",
  },

  // ---------- Wrist Watches ----------
  {
    name: "Moonphase Chronograph Leather Watch",
    brand: "Aurelian",
    category: "Wrist Watches",
    price: 189.99,
    listPrice: 229.99,
    countInStock: 16,
    numSales: 35,
    tags: ["featured", "todays-deal"],
    sizes: [],
    colors: ["Gold", "Brown"],
    shots: 3,
    description:
      "A 40 mm gold-tone case with a silver dial, three chronograph sub-dials and a moonphase window. Paired with a brown alligator-embossed leather strap and a deployant clasp. Water resistant to 50 m.",
  },
  {
    name: "Steel Chronograph Bracelet Watch",
    brand: "Kessler & Co.",
    category: "Wrist Watches",
    price: 249.99,
    countInStock: 12,
    numSales: 27,
    tags: ["best-seller"],
    sizes: [],
    colors: ["Silver", "Black"],
    shots: 3,
    description:
      "Brushed stainless steel with a black dial, Roman numerals and a day-date display. The solid link bracelet closes with a push-button clasp. Scratch-resistant sapphire crystal and 100 m water resistance.",
  },
  {
    name: "Rose Gold Black Dial Dress Watch",
    brand: "Aurelian",
    category: "Wrist Watches",
    price: 219.99,
    countInStock: 14,
    numSales: 22,
    tags: ["new-arrival"],
    sizes: [],
    colors: ["Rose Gold", "Black"],
    shots: 3,
    description:
      "A slim rose-gold case framing a guilloché black dial with a small-seconds sub-dial. Black leather strap with contrast stitching. Understated enough for every day, elegant enough for a suit.",
  },
  {
    name: "Rose Gold Moonphase Dress Watch",
    brand: "Aurelian",
    category: "Wrist Watches",
    price: 239.99,
    countInStock: 10,
    numSales: 31,
    tags: ["best-seller", "featured"],
    sizes: [],
    colors: ["Rose Gold", "Brown"],
    shots: 3,
    description:
      "An ivory dial with a deep-blue moonphase display, set in a polished rose-gold case on a dark brown leather strap. Japanese automatic movement with a 40-hour power reserve.",
  },
  {
    name: "Two-Tone Fluted Bezel Watch",
    brand: "Kessler & Co.",
    category: "Wrist Watches",
    price: 279.99,
    listPrice: 329.99,
    countInStock: 9,
    numSales: 18,
    tags: ["todays-deal"],
    sizes: [],
    colors: ["Silver", "Gold"],
    shots: 3,
    description:
      "Steel and gold-tone jubilee bracelet, a fluted gold bezel and a slate dial with a magnified date window. A timeless two-tone look that works with both silver and gold jewellery.",
  },
  {
    name: "Black Dial Dive Watch",
    brand: "Kessler & Co.",
    category: "Wrist Watches",
    price: 299.99,
    countInStock: 13,
    numSales: 26,
    tags: ["featured"],
    sizes: [],
    colors: ["Black", "Gold"],
    shots: 3,
    description:
      "A 41 mm diver with a unidirectional ceramic bezel, luminous hands and markers, and a screw-down crown rated to 200 m. The two-tone oyster bracelet has a fold-over safety clasp.",
  },
  {
    name: "Minimal Steel Automatic Watch",
    brand: "Nordvik",
    category: "Wrist Watches",
    price: 199.99,
    countInStock: 19,
    numSales: 14,
    tags: ["new-arrival"],
    sizes: [],
    colors: ["Silver", "Black"],
    shots: 3,
    description:
      "Scandinavian minimalism in brushed steel: a black sunray dial, applied baton markers and an exhibition case back that shows the automatic movement. Integrated steel bracelet.",
  },
  {
    name: "Blue Dial Gold Mesh Watch",
    brand: "Aurelian",
    category: "Wrist Watches",
    price: 159.99,
    countInStock: 20,
    numSales: 39,
    tags: ["best-seller"],
    sizes: [],
    colors: ["Gold", "Blue"],
    shots: 3,
    description:
      "A women's 36 mm watch with a midnight-blue dial, Roman numerals and a slim gold-tone link bracelet. Quartz movement, mineral crystal and 30 m water resistance.",
  },
  {
    name: "Slim Steel Link Women's Watch",
    brand: "Nordvik",
    category: "Wrist Watches",
    price: 129.99,
    listPrice: 149.99,
    countInStock: 23,
    numSales: 44,
    tags: ["todays-deal"],
    sizes: [],
    colors: ["Silver", "Black"],
    shots: 3,
    description:
      "A petite 32 mm case, a clean black dial and a fine seven-link steel bracelet. Light, comfortable and easy to dress up or down.",
  },

  // ---------- Sunglasses ----------
  {
    name: "Tortoise Clubmaster Sunglasses",
    brand: "Shade & Co.",
    category: "Sunglasses",
    price: 34.99,
    countInStock: 45,
    numSales: 92,
    tags: ["best-seller"],
    sizes: [],
    colors: ["Brown", "Green"],
    shots: 3,
    description:
      "Tortoiseshell acetate brows on a gold metal frame, with dark green UV400 lenses. A retro shape that suits most faces. Comes with a hard case and a microfibre cloth.",
  },
  {
    name: "Gradient Aviator Sunglasses",
    brand: "Shade & Co.",
    category: "Sunglasses",
    price: 29.99,
    listPrice: 39.99,
    countInStock: 52,
    numSales: 68,
    tags: ["todays-deal"],
    sizes: [],
    colors: ["Gold", "Blue"],
    shots: 3,
    description:
      "The classic teardrop aviator in a thin gold frame, with blue-to-clear gradient lenses and adjustable nose pads. 100% UV400 protection.",
  },
  {
    name: "Green Lens Double-Bridge Aviators",
    brand: "Shade & Co.",
    category: "Sunglasses",
    price: 36.99,
    countInStock: 28,
    numSales: 21,
    tags: ["new-arrival"],
    sizes: [],
    colors: ["Black", "Green"],
    shots: 3,
    description:
      "A modern hexagonal aviator with a matte black double bridge and tinted green lenses. Lightweight metal frame with spring hinges for a comfortable fit.",
  },
  {
    name: "Clear Oversized Shield Sunglasses",
    brand: "Mode Optics",
    category: "Sunglasses",
    price: 27.99,
    countInStock: 34,
    numSales: 17,
    tags: ["featured", "new-arrival"],
    sizes: [],
    colors: ["Clear"],
    shots: 3,
    description:
      "An oversized, flat-top frame in crystal-clear acetate with gold stud details. A fashion-forward statement for festival season.",
  },

  // ---------- Dresses ----------
  {
    name: "Polka Dot Skater Dress",
    brand: "Bloom",
    category: "Dresses",
    price: 39.99,
    countInStock: 27,
    numSales: 33,
    tags: ["new-arrival"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Light Blue"],
    shots: 4,
    description:
      "A cheerful fit-and-flare dress in soft cotton with a scattered blue polka-dot print. Cap sleeves, a fitted bodice and a full, twirl-ready skirt. Concealed back zip.",
  },
  {
    name: "Palm Print Off-Shoulder Maxi Dress",
    brand: "Casa Brisa",
    category: "Dresses",
    price: 49.99,
    listPrice: 64.99,
    countInStock: 22,
    numSales: 47,
    tags: ["todays-deal", "best-seller"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["White", "Black"],
    shots: 4,
    description:
      "A flowing maxi in lightweight crepe with a bold black palm-leaf print. The ruffled off-shoulder neckline and adjustable straps make it perfect for holidays and summer evenings.",
  },
  {
    name: "Button-Front Linen Midi Dress",
    brand: "Linea",
    category: "Dresses",
    price: 54.99,
    countInStock: 25,
    numSales: 28,
    tags: ["new-arrival"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Beige"],
    shots: 4,
    description:
      "Breathable linen-blend midi in a natural stone shade. Sleeveless with a scoop neck, a full button front and a tie waist. Effortless with sandals by day or heels at night.",
  },
  {
    name: "Strapless Tiered Bow Dress",
    brand: "Bloom",
    category: "Dresses",
    price: 44.99,
    countInStock: 18,
    numSales: 25,
    tags: ["featured"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Sage Green"],
    shots: 4,
    description:
      "A sage-green strapless dress with a boned bodice, a tiered ruffle skirt and a sash that ties in a bow at the waist. Ideal for garden parties and engagements.",
  },
  {
    name: "Tartan Bow Sash Dress",
    brand: "Bloom",
    category: "Dresses",
    price: 42.99,
    countInStock: 20,
    numSales: 34,
    tags: ["best-seller"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Grey", "Black"],
    shots: 4,
    description:
      "Black-and-white tartan cotton with a sleeveless fitted top, a full skirt and a black satin sash. Polished and playful at the same time.",
  },
  {
    name: "Floral Off-Shoulder Evening Gown",
    brand: "Maison Lune",
    category: "Dresses",
    price: 129.99,
    listPrice: 159.99,
    countInStock: 8,
    numSales: 19,
    tags: ["featured", "todays-deal"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Black", "Multicolor"],
    shots: 4,
    description:
      "A floor-length gown in black satin covered in painterly pink, blue and teal florals. The structured off-shoulder bodice flows into a full A-line skirt. Fully lined.",
  },
  {
    name: "Red Leather Corset Maxi Dress",
    brand: "Velour",
    category: "Dresses",
    price: 89.99,
    countInStock: 12,
    numSales: 16,
    tags: ["new-arrival"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Red"],
    shots: 4,
    description:
      "A vegan-leather corset bodice paired with a flowing red satin maxi skirt. Dramatic, confident and made to be noticed. Back lace-up for an adjustable fit.",
  },
  {
    name: "Black Leather Corset Maxi Dress",
    brand: "Velour",
    category: "Dresses",
    price: 84.99,
    countInStock: 15,
    numSales: 30,
    tags: ["best-seller"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Black"],
    shots: 4,
    description:
      "The all-black version of our best-selling corset dress: a sculpted vegan-leather bodice over a fluid satin skirt. Wear with heels for evening or boots for an edgier look.",
  },
  {
    name: "Polka Dot Strapless Ball Dress",
    brand: "Maison Lune",
    category: "Dresses",
    price: 79.99,
    listPrice: 99.99,
    countInStock: 10,
    numSales: 22,
    tags: ["todays-deal"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["White", "Black"],
    shots: 4,
    description:
      "A 1950s-inspired strapless dress in white with tiny black dots, a scalloped neckline, a bow at the waist and a voluminous tulle-lined skirt.",
  },
  {
    name: "Colour-Block Maxi Dress",
    brand: "Marni",
    category: "Dresses",
    price: 179.99,
    countInStock: 7,
    numSales: 9,
    tags: ["new-arrival", "featured"],
    sizes: CLOTHING.slice(0, 5),
    colors: ["Burgundy", "Pink", "Black"],
    shots: 4,
    description:
      "An artful maxi dress with a burgundy front, black back and mismatched pink and ivory sleeves. Straight, column silhouette in fluid crepe. A true statement piece.",
  },
];

const images = (slug: string, p: SeedProduct) => [
  ...Array.from({ length: p.shots ?? 0 }, (_, i) => `/images/products/${slug}/${i + 1}.webp`),
  ...Array.from({ length: p.looks ?? 0 }, (_, i) => `/images/products/${slug}/look-${i + 1}.jpg`),
];

// `shots` / `looks` are dropped by the schema on insert.
export const products = catalog.map((p) => {
  const slug = toSlug(p.name);
  return { ...p, slug, images: images(slug, p), listPrice: p.listPrice ?? 0, isPublished: true };
});
